version: '3.3'

services:
  db:
    container_name: social
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: SuperPassword
      DATABASE_URL: 'postgresql://postgres:SuperPassword@localhost:5432/diplom'
    
